ci: Fix errors on sanitizer doctest
```
   Doc-tests atomic_memcpy
error: mixing `-Zsanitizer` will cause an ABI mismatch in crate `atomic_memcpy`
 --> src/lib.rs:3:1
  |
3 | /*!
  | ^
  |
  = help: the `-Zsanitizer` flag modifies the ABI so Rust crates compiled with different values of this flag cannot be used together safely
  = note: unset `-Zsanitizer` in this crate is incompatible with `-Zsanitizer=memory` in dependency `core`
  = help: set `-Zsanitizer=memory` in this crate or unset `-Zsanitizer` in `core`
  = help: if you are sure this will not cause problems, you may use `-Cunsafe-allow-abi-mismatch=sanitizer` to silence this error

error: mixing `-Zsanitizer` will cause an ABI mismatch in crate `atomic_memcpy`
 --> src/lib.rs:3:1
  |
3 | /*!
  | ^
  |
  = help: the `-Zsanitizer` flag modifies the ABI so Rust crates compiled with different values of this flag cannot be used together safely
  = note: unset `-Zsanitizer` in this crate is incompatible with `-Zsanitizer=memory` in dependency `compiler_builtins`
  = help: set `-Zsanitizer=memory` in this crate or unset `-Zsanitizer` in `compiler_builtins`
  = help: if you are sure this will not cause problems, you may use `-Cunsafe-allow-abi-mismatch=sanitizer` to silence this error
```