Temporarily disable AVR build
LLVM 16 broke AVR.

```
LLVM ERROR: Expected a constant shift amount!
error: could not compile `compiler_builtins` (lib)
```