ci:  Temporarily disable asan and msan with fat LTO
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3334==ERROR: AddressSanitizer: SEGV on unknown address 0x02000d2ef240 (pc 0x555e01b0afc7 bp 0x7ffc430de1b0 sp 0x7ffc430de100 T0)
==3334==The signal is caused by a READ memory access.
    #0 0x555e01b0afc7  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-04c46d82177f025f+0x186fc7) (BuildId: 29923f56aa27c9d06e08f73052eb3efbd82fedaf)
    #1 0x7fdf4de2a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #2 0x7fdf4de2a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #3 0x555e01a56014  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-04c46d82177f025f+0xd2014) (BuildId: 29923f56aa27c9d06e08f73052eb3efbd82fedaf)

==3334==Register values:
rax = 0x000001ff8d2f7240  rbx = 0x00007ffc430de100  rcx = 0x0000000000000000  rdx = 0x000000008fff6fff
rdi = 0x00007fdf4be09010  rsi = 0x0000000000000000  rbp = 0x00007ffc430de1b0  rsp = 0x00007ffc430de100
 r8 = 0x00000ffc697b9200   r9 = 0x0000000000000000  r10 = 0xafffff00000fff01  r11 = 0x4000000000000000
r12 = 0x00007ffc430de2d8  r13 = 0x0000000000000001  r14 = 0x00007fdf4be09000  r15 = 0x00000ffbe97c1200
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-04c46d82177f025f+0x186fc7) (BuildId: 29923f56aa27c9d06e08f73052eb3efbd82fedaf)
==3334==ABORTING
error: test failed, to rerun pass `-p atomic-memcpy --lib`

Caused by:
  process didn't exit successfully: `/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-04c46d82177f025f` (exit status: 1)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```

```
MemorySanitizer init done
MemorySanitizer:DEADLYSIGNAL
==3315==ERROR: MemorySanitizer: SEGV on unknown address 0x6fff3618a3d8 (pc 0x55a3c90d218a bp 0x000000000000 sp 0x7fff3618a1b0 T3315)
==3315==The signal is caused by a READ memory access.
    #0 0x55a3c90d218a  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158+0x15f18a) (BuildId: eb746f488bb9238cde720cedbf7039f80464d20d)
    #1 0x55a3c90d1b56  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158+0x15eb56) (BuildId: eb746f488bb9238cde720cedbf7039f80464d20d)
    #2 0x55a3c903f0ec  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158+0xcc0ec) (BuildId: eb746f488bb9238cde720cedbf7039f80464d20d)
    #3 0x7fd98962a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #4 0x7fd98962a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #5 0x55a3c8fcc214  (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158+0x59214) (BuildId: eb746f488bb9238cde720cedbf7039f80464d20d)

==3315==Register values:
rax = 0x0000000080000003  rbx = 0x0000500000000000  rcx = 0x00006fff3618a3d8  rdx = 0x0000100000000000
rdi = 0x00007fff3618a3d0  rsi = 0x00002fff3618a3d0  rbp = 0x0000000000000000  rsp = 0x00007fff3618a1b0
 r8 = 0x00006fff3618a3d0   r9 = 0x0000000000000000  r10 = 0x000055a3c8f8f0bf  r11 = 0x0000000000000206
r12 = 0x0000500000000000  r13 = 0x00002fff3618a3a0  r14 = 0x00007fff3618a3d0  r15 = 0xffffffffffffef60
MemorySanitizer can not provide additional info.
SUMMARY: MemorySanitizer: SEGV (/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158+0x15f18a) (BuildId: eb746f488bb9238cde720cedbf7039f80464d20d)
==3315==ABORTING
error: test failed, to rerun pass `-p atomic-memcpy --lib`

Caused by:
  process didn't exit successfully: `/home/runner/work/atomic-memcpy/atomic-memcpy/target/x86_64-unknown-linux-gnu/release/deps/atomic_memcpy-0e0b4cc066b47158` (exit status: 1)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```